<?xml version="1.0" encoding="utf-8"?><Database Name="QLCT" Class="QLCTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-2SERJAO\SQLEXPRESS;Initial Catalog=QLCT;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLCTConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PassWord" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NumberSup" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IdDepartment" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumberCus" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_Department" Member="Departments" ThisKey="Id" OtherKey="IdHeader" Type="Department" />
      <Association Name="User_Supplier" Member="Suppliers" ThisKey="Id" OtherKey="IdStaff" Type="Supplier" />
      <Association Name="User_Guarantee" Member="Guarantees" ThisKey="Id" OtherKey="IdStaff" Type="Guarantee" />
      <Association Name="User_Customer" Member="Customers" ThisKey="Id" OtherKey="IdStaff" Type="Customer" />
      <Association Name="User_Bill" Member="Bills" ThisKey="Id" OtherKey="IdUser" Type="Bill" />
      <Association Name="Department_User" Member="Department" ThisKey="IdDepartment" OtherKey="Id" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NumberStaff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdHeader" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Department_User" Member="Users" ThisKey="Id" OtherKey="IdDepartment" Type="User" />
      <Association Name="User_Department" Member="User" ThisKey="IdHeader" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Notify" Member="Notifies">
    <Type Name="Notify">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Decription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateTake" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NotifyType_Notify" Member="NotifyType" ThisKey="TypeId" OtherKey="Id" Type="NotifyType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NotifyType" Member="NotifyTypes">
    <Type Name="NotifyType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="NotifyType_Notify" Member="Notifies" ThisKey="Id" OtherKey="TypeId" Type="Notify" />
    </Type>
  </Table>
  <Table Name="dbo.Supplier" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdStaff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Debt" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BankNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BankAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Supplier" Member="User" ThisKey="IdStaff" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Guarantee" Member="Guarantees">
    <Type Name="Guarantee">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdDetailsBill" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdStaff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UrlGuarantee" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_Guarantee" Member="User" ThisKey="IdStaff" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="DetailsBill_Guarantee" Member="DetailsBill" ThisKey="IdDetailsBill" OtherKey="Id" Type="DetailsBill" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdStaff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Debt" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BankNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BankAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeOfDebt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Customer_Bill" Member="Bills" ThisKey="Id" OtherKey="IdCustormer" Type="Bill" />
      <Association Name="User_Customer" Member="User" ThisKey="IdStaff" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NumberRemain" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Discount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MonthOfGuarantee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_DetailsBill" Member="DetailsBills" ThisKey="Id" OtherKey="IdProduct" Type="DetailsBill" />
    </Type>
  </Table>
  <Table Name="dbo.Bill" Member="Bills">
    <Type Name="Bill">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameBill" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCustormer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UrlBill" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddDelivery" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TypeOfBill" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdStaffGuarantee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Totalpay" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Deposit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TypeOfDebt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Debt" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="Bill_DetailsBill" Member="DetailsBills" ThisKey="Id" OtherKey="IdBill" Type="DetailsBill" />
      <Association Name="Customer_Bill" Member="Customer" ThisKey="IdCustormer" OtherKey="Id" Type="Customer" IsForeignKey="true" />
      <Association Name="User_Bill" Member="User" ThisKey="IdUser" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DetailsBill" Member="DetailsBills">
    <Type Name="DetailsBill">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdBill" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdProduct" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Number" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="DetailsBill_Guarantee" Member="Guarantees" ThisKey="Id" OtherKey="IdDetailsBill" Type="Guarantee" />
      <Association Name="Bill_DetailsBill" Member="Bill" ThisKey="IdBill" OtherKey="Id" Type="Bill" IsForeignKey="true" />
      <Association Name="Product_DetailsBill" Member="Product" ThisKey="IdProduct" OtherKey="Id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
</Database>